### ISSUE TITLE
deployment template in chart missing requests and limits

### ISSUE THREAD

**Issue by timroster** [cloud-native-toolkit/terraform-gitops-watson-nlp#12]
This can help the scheduler in correctly planning the deployment and provide an example for customization. If there is no specific guidance from offering team something like:

```yaml
resources:
  requests:
    memory: "1024Mi"
    cpu: "250m"
  limits:
    memory: "2048Mi"
    cpu: "2000m"
```

Since the container also is using ephemeral storage, there may be a benefit to setting a limit on that too: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#configurations-for-local-ephemeral-storage
